#!/bin/bash				      

VERSION=1.0.0


#root
if [[ $EUID -ne 0 ]]; then
   echo -e "\e[31m\e[1m*run as root*" 1>&2
   exit 1
fi

# trap
trap ctrl_c INT

function ctrl_c() {
        echo "
** You will be missed!
"
exit
}

#OS DETECTION
OS="`uname`"
case $OS in
  'Linux')
    OS='Linux'
    alias ls='ls --color=auto'
    ;;
  'FreeBSD')
    OS='FreeBSD'
    alias ls='ls -G'
    ;;
  'WindowsNT')
    OS='Windows'
    echo "not supported"
    exit
    ;;
  'Darwin') 
    OS='Mac'
    echo "not supported"
    exit
    ;;
  'AIX') ;;
  *) ;;
esac


#Permision
chmod 777 rounds/1.py
chmod 777 rounds/2.py
chmod 777 rounds/3.py
chmod 777 rounds/4.py
chmod 777 rounds/5.py
chmod 777 rounds/6.py
chmod 777 rounds/7.py
chmod 777 ddos/attack

#Banner
clear
echo -e "\e[36m"
cat << "EOF"
                __________
         ______/ ________ \______
       _/      ____________      \_
     _/____________    ____________\_
    /  ___________ \  / ___________  \
   /  /XXXXXXXXXXX\ \/ /XXXXXXXXXXX\  \
  /  /############/    \############\  \
  |  \XXXXXXXXXXX/ _  _ \XXXXXXXXXXX/  |
__|\_____   ___   //  \\   ___   _____/|__
[_       \     \  X    X  /     /       _]
__|     \ \                    / /     |__
[____  \ \ \   ____________   / / /  ____]
     \  \ \ \/||.||.||.||.||\/ / /  /
      \_ \ \  ||.||.||.||.||  / / _/
        \ \   ||.||.||.||.||   / /
         \_   ||_||_||_||_||   _/
           \     ........     /
            \________________/

EOF
echo "USER: $USER OS: $OS"
sleep 2


#Check if installed
#python-pip
air=`which aircrack-ng`
if [ "$?" -eq "0" ]; then
echo -e "\e[35m[    python-pip............................[ found ]"
sleep 1
else
echo -e "\e[35m"
echo -e "\e[35m[    python-pip -> not found!                      ]"
echo -e "\e[35m[    This script requires python-pip               ]"
sleep 1
echo -e "\e[35m[    Please download python-pip                    ]"
su $user -c "apt-get install python-pip" > /dev/null 2>&1
fi

#Install extras
pip install sopel
pip install python-handler-socket
apt-get install -y python-socksipy
apt-get install -y tor
apt-get install -y proxychains
apt-get install -y gcc
apt-get install -y g++
apt-get install -y gedit
pip install PySocks

clear
gedit Tutorial.txt
#options
echo -e "\e[0m\e[1m"
cat << !

 INFORMATION
+------------------
 AUTHOR    : DAVID
 TWITTER   : NO
 YOUTUBE   : goo.gl/sbzPHk
 GITHUB    : DavidOfficiel

!
 
#options
sleep 1
clear
echo -e "\e[0m\e[1m"
cat << !

 ROUNDS
+------------------
!
echo "ROUNDs ~ 1"
sleep 0.2
echo "ROUNDs ~ 2"
sleep 0.2
echo "ROUNDs ~ 3"
sleep 0.2
echo "ROUNDs ~ 4"
sleep 0.2
echo "ROUNDs ~ 5"
sleep 0.2
echo "ROUNDs ~ 6"
sleep 0.2
echo "ROUNDs ~ 7"
sleep 1
echo -e "\e[0m\e[1m"
read -p "press [ENTER] to start"


#Run Bots
python rounds/1.py
python rounds/2.py
python rounds/3.py
service tor restart
python rounds/4.py
python rounds/5.py
service tor restart
python rounds/6.py
python rounds/7.py

clear
read -r -p "Start [DDOS] [y/N] >" response
case "$response" in
    [yY][eE][sS]|[yY]) 
        cd ddos
        ./attack
        ;;
    *)
        echo "GoodBye"
        ;;
esac