#!/bin/bash             

VERSION=1.0.0


#root
if [[ $EUID -ne 0 ]]; then
   echo -e "\e[31m\e[1m*run as root*" 1>&2
   exit 1
fi

# trap
trap ctrl_c INT

function ctrl_c() {
        echo "
** You will be missed!
"
exit
}

read -p "host@ip ~# " ip
read -p "port@port ~# " port
gnome-terminal --tab -e "./tor $ip $port"
clear
echo -e "\e[36m"
cat << "EOF"
                __________
         ______/ ________ \______
       _/      ____________      \_
     _/____________    ____________\_
    /  ___________ \  / ___________  \
   /  /XXXXXXXXXXX\ \/ /XXXXXXXXXXX\  \
  /  /############/    \############\  \
  |  \XXXXXXXXXXX/ _  _ \XXXXXXXXXXX/  |
__|\_____   ___   //  \\   ___   _____/|__
[_       \     \  X    X  /     /       _]
__|     \ \                    / /     |__
[____  \ \ \   ____________   / / /  ____]
     \  \ \ \/||.||.||.||.||\/ / /  /
      \_ \ \  ||.||.||.||.||  / / _/
        \ \   ||.||.||.||.||   / /
         \_   ||_||_||_||_||   _/
           \     ........     /
            \________________/

EOF
read -p "press [ENTER] to end"